language: node_js
node_js:
  - "14"
  - "12"
  - "10"
before_install:
  - 'nvm install-latest-npm'
install:
  - 'if [ -n "${PACKAGE-}" ]; then cd "packages/${PACKAGE}"; fi'
  - 'if [ "${TRAVIS_NODE_VERSION}" = "0.6" ] || [ "${TRAVIS_NODE_VERSION}" = "0.9" ]; then nvm install --latest-npm 0.8 && npm install && nvm use "${TRAVIS_NODE_VERSION}"; else npm install; fi;'
  - 'if [ -n "${ESLINT}" ]; then npm install --no-save "eslint@${ESLINT}"; fi'
script:
  - 'if [ -n "${PREPUBLISH-}" ]; then npm run pretravis && npm run prepublish && npm run posttravis; elif [ -n "${LINT-}" ]; then npm run lint; else npm run travis; fi'
sudo: false
env:
  matrix:
  - 'TEST=true ESLINT=5 PACKAGE=@paysera/eslint-config-base'
  - 'TEST=true ESLINT=5 PACKAGE=@paysera/eslint-config'
  - 'TEST=true ESLINT=6 PACKAGE=@paysera/eslint-config-base'
  - 'TEST=true ESLINT=6 PACKAGE=@paysera/eslint-config'
  - 'TEST=true ESLINT=7 PACKAGE=@paysera/eslint-config-base'
  - 'TEST=true ESLINT=7 PACKAGE=@paysera/eslint-config'
matrix:
  fast_finish: true
  include:
  - node_js: "lts/*"
    env: PREPUBLISH=true ESLINT=5 PACKAGE=@paysera/eslint-config-base
  - node_js: "lts/*"
    env: PREPUBLISH=true ESLINT=5 PACKAGE=@paysera/eslint-config
  - node_js: "lts/*"
    env: PREPUBLISH=true ESLINT=6 PACKAGE=@paysera/eslint-config-base
  - node_js: "lts/*"
    env: PREPUBLISH=true ESLINT=6 PACKAGE=@paysera/eslint-config
  - node_js: "lts/*"
    env: LINT=true
  - node_js: "lts/*"
    env: PREPUBLISH=true ESLINT=7 PACKAGE=@paysera/eslint-config-base
  - node_js: "lts/*"
    env: PREPUBLISH=true ESLINT=7 PACKAGE=@paysera/eslint-config
  - node_js: "lts/*"
    env: LINT=true
  exclude:
  allow_failures:
  - env: PREPUBLISH=true ESLINT=5 PACKAGE=@paysera/eslint-config-base
  - env: PREPUBLISH=true ESLINT=5 PACKAGE=@paysera/eslint-config
  - env: PREPUBLISH=true ESLINT=6 PACKAGE=@paysera/eslint-config-base
  - env: PREPUBLISH=true ESLINT=6 PACKAGE=@paysera/eslint-config
